/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.emi.events.catalog;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ContentPurchasedEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5049105529365657588L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ContentPurchasedEvent\",\"namespace\":\"com.emi.events.catalog\",\"fields\":[{\"name\":\"bookId\",\"type\":\"string\"},{\"name\":\"userId\",\"type\":\"string\"},{\"name\":\"chapterIds\",\"type\":{\"type\":\"array\",\"items\":\"string\"},\"default\":[]},{\"name\":\"type\",\"type\":[\"null\",{\"type\":\"enum\",\"name\":\"OrderType\",\"symbols\":[\"BOOK\",\"CONTENT\"]}],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ContentPurchasedEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ContentPurchasedEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ContentPurchasedEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ContentPurchasedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ContentPurchasedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ContentPurchasedEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ContentPurchasedEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ContentPurchasedEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ContentPurchasedEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence bookId;
  private java.lang.CharSequence userId;
  private java.util.List<java.lang.CharSequence> chapterIds;
  private com.emi.events.catalog.OrderType type;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ContentPurchasedEvent() {}

  /**
   * All-args constructor.
   * @param bookId The new value for bookId
   * @param userId The new value for userId
   * @param chapterIds The new value for chapterIds
   * @param type The new value for type
   */
  public ContentPurchasedEvent(java.lang.CharSequence bookId, java.lang.CharSequence userId, java.util.List<java.lang.CharSequence> chapterIds, com.emi.events.catalog.OrderType type) {
    this.bookId = bookId;
    this.userId = userId;
    this.chapterIds = chapterIds;
    this.type = type;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return bookId;
    case 1: return userId;
    case 2: return chapterIds;
    case 3: return type;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: bookId = (java.lang.CharSequence)value$; break;
    case 1: userId = (java.lang.CharSequence)value$; break;
    case 2: chapterIds = (java.util.List<java.lang.CharSequence>)value$; break;
    case 3: type = (com.emi.events.catalog.OrderType)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'bookId' field.
   * @return The value of the 'bookId' field.
   */
  public java.lang.CharSequence getBookId() {
    return bookId;
  }


  /**
   * Sets the value of the 'bookId' field.
   * @param value the value to set.
   */
  public void setBookId(java.lang.CharSequence value) {
    this.bookId = value;
  }

  /**
   * Gets the value of the 'userId' field.
   * @return The value of the 'userId' field.
   */
  public java.lang.CharSequence getUserId() {
    return userId;
  }


  /**
   * Sets the value of the 'userId' field.
   * @param value the value to set.
   */
  public void setUserId(java.lang.CharSequence value) {
    this.userId = value;
  }

  /**
   * Gets the value of the 'chapterIds' field.
   * @return The value of the 'chapterIds' field.
   */
  public java.util.List<java.lang.CharSequence> getChapterIds() {
    return chapterIds;
  }


  /**
   * Sets the value of the 'chapterIds' field.
   * @param value the value to set.
   */
  public void setChapterIds(java.util.List<java.lang.CharSequence> value) {
    this.chapterIds = value;
  }

  /**
   * Gets the value of the 'type' field.
   * @return The value of the 'type' field.
   */
  public com.emi.events.catalog.OrderType getType() {
    return type;
  }


  /**
   * Sets the value of the 'type' field.
   * @param value the value to set.
   */
  public void setType(com.emi.events.catalog.OrderType value) {
    this.type = value;
  }

  /**
   * Creates a new ContentPurchasedEvent RecordBuilder.
   * @return A new ContentPurchasedEvent RecordBuilder
   */
  public static com.emi.events.catalog.ContentPurchasedEvent.Builder newBuilder() {
    return new com.emi.events.catalog.ContentPurchasedEvent.Builder();
  }

  /**
   * Creates a new ContentPurchasedEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ContentPurchasedEvent RecordBuilder
   */
  public static com.emi.events.catalog.ContentPurchasedEvent.Builder newBuilder(com.emi.events.catalog.ContentPurchasedEvent.Builder other) {
    if (other == null) {
      return new com.emi.events.catalog.ContentPurchasedEvent.Builder();
    } else {
      return new com.emi.events.catalog.ContentPurchasedEvent.Builder(other);
    }
  }

  /**
   * Creates a new ContentPurchasedEvent RecordBuilder by copying an existing ContentPurchasedEvent instance.
   * @param other The existing instance to copy.
   * @return A new ContentPurchasedEvent RecordBuilder
   */
  public static com.emi.events.catalog.ContentPurchasedEvent.Builder newBuilder(com.emi.events.catalog.ContentPurchasedEvent other) {
    if (other == null) {
      return new com.emi.events.catalog.ContentPurchasedEvent.Builder();
    } else {
      return new com.emi.events.catalog.ContentPurchasedEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for ContentPurchasedEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ContentPurchasedEvent>
    implements org.apache.avro.data.RecordBuilder<ContentPurchasedEvent> {

    private java.lang.CharSequence bookId;
    private java.lang.CharSequence userId;
    private java.util.List<java.lang.CharSequence> chapterIds;
    private com.emi.events.catalog.OrderType type;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.emi.events.catalog.ContentPurchasedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.bookId)) {
        this.bookId = data().deepCopy(fields()[0].schema(), other.bookId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.userId)) {
        this.userId = data().deepCopy(fields()[1].schema(), other.userId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.chapterIds)) {
        this.chapterIds = data().deepCopy(fields()[2].schema(), other.chapterIds);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.type)) {
        this.type = data().deepCopy(fields()[3].schema(), other.type);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing ContentPurchasedEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.emi.events.catalog.ContentPurchasedEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.bookId)) {
        this.bookId = data().deepCopy(fields()[0].schema(), other.bookId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.userId)) {
        this.userId = data().deepCopy(fields()[1].schema(), other.userId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.chapterIds)) {
        this.chapterIds = data().deepCopy(fields()[2].schema(), other.chapterIds);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.type)) {
        this.type = data().deepCopy(fields()[3].schema(), other.type);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'bookId' field.
      * @return The value.
      */
    public java.lang.CharSequence getBookId() {
      return bookId;
    }


    /**
      * Sets the value of the 'bookId' field.
      * @param value The value of 'bookId'.
      * @return This builder.
      */
    public com.emi.events.catalog.ContentPurchasedEvent.Builder setBookId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.bookId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'bookId' field has been set.
      * @return True if the 'bookId' field has been set, false otherwise.
      */
    public boolean hasBookId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'bookId' field.
      * @return This builder.
      */
    public com.emi.events.catalog.ContentPurchasedEvent.Builder clearBookId() {
      bookId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'userId' field.
      * @return The value.
      */
    public java.lang.CharSequence getUserId() {
      return userId;
    }


    /**
      * Sets the value of the 'userId' field.
      * @param value The value of 'userId'.
      * @return This builder.
      */
    public com.emi.events.catalog.ContentPurchasedEvent.Builder setUserId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.userId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'userId' field has been set.
      * @return True if the 'userId' field has been set, false otherwise.
      */
    public boolean hasUserId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'userId' field.
      * @return This builder.
      */
    public com.emi.events.catalog.ContentPurchasedEvent.Builder clearUserId() {
      userId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'chapterIds' field.
      * @return The value.
      */
    public java.util.List<java.lang.CharSequence> getChapterIds() {
      return chapterIds;
    }


    /**
      * Sets the value of the 'chapterIds' field.
      * @param value The value of 'chapterIds'.
      * @return This builder.
      */
    public com.emi.events.catalog.ContentPurchasedEvent.Builder setChapterIds(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[2], value);
      this.chapterIds = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'chapterIds' field has been set.
      * @return True if the 'chapterIds' field has been set, false otherwise.
      */
    public boolean hasChapterIds() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'chapterIds' field.
      * @return This builder.
      */
    public com.emi.events.catalog.ContentPurchasedEvent.Builder clearChapterIds() {
      chapterIds = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'type' field.
      * @return The value.
      */
    public com.emi.events.catalog.OrderType getType() {
      return type;
    }


    /**
      * Sets the value of the 'type' field.
      * @param value The value of 'type'.
      * @return This builder.
      */
    public com.emi.events.catalog.ContentPurchasedEvent.Builder setType(com.emi.events.catalog.OrderType value) {
      validate(fields()[3], value);
      this.type = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'type' field has been set.
      * @return True if the 'type' field has been set, false otherwise.
      */
    public boolean hasType() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'type' field.
      * @return This builder.
      */
    public com.emi.events.catalog.ContentPurchasedEvent.Builder clearType() {
      type = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ContentPurchasedEvent build() {
      try {
        ContentPurchasedEvent record = new ContentPurchasedEvent();
        record.bookId = fieldSetFlags()[0] ? this.bookId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.userId = fieldSetFlags()[1] ? this.userId : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.chapterIds = fieldSetFlags()[2] ? this.chapterIds : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[2]);
        record.type = fieldSetFlags()[3] ? this.type : (com.emi.events.catalog.OrderType) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ContentPurchasedEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<ContentPurchasedEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ContentPurchasedEvent>
    READER$ = (org.apache.avro.io.DatumReader<ContentPurchasedEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.bookId);

    out.writeString(this.userId);

    long size0 = this.chapterIds.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (java.lang.CharSequence e0: this.chapterIds) {
      actualSize0++;
      out.startItem();
      out.writeString(e0);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

    if (this.type == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeEnum(this.type.ordinal());
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.bookId = in.readString(this.bookId instanceof Utf8 ? (Utf8)this.bookId : null);

      this.userId = in.readString(this.userId instanceof Utf8 ? (Utf8)this.userId : null);

      long size0 = in.readArrayStart();
      java.util.List<java.lang.CharSequence> a0 = this.chapterIds;
      if (a0 == null) {
        a0 = new SpecificData.Array<java.lang.CharSequence>((int)size0, SCHEMA$.getField("chapterIds").schema());
        this.chapterIds = a0;
      } else a0.clear();
      SpecificData.Array<java.lang.CharSequence> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.CharSequence>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          java.lang.CharSequence e0 = (ga0 != null ? ga0.peek() : null);
          e0 = in.readString(e0 instanceof Utf8 ? (Utf8)e0 : null);
          a0.add(e0);
        }
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.type = null;
      } else {
        this.type = com.emi.events.catalog.OrderType.values()[in.readEnum()];
      }

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.bookId = in.readString(this.bookId instanceof Utf8 ? (Utf8)this.bookId : null);
          break;

        case 1:
          this.userId = in.readString(this.userId instanceof Utf8 ? (Utf8)this.userId : null);
          break;

        case 2:
          long size0 = in.readArrayStart();
          java.util.List<java.lang.CharSequence> a0 = this.chapterIds;
          if (a0 == null) {
            a0 = new SpecificData.Array<java.lang.CharSequence>((int)size0, SCHEMA$.getField("chapterIds").schema());
            this.chapterIds = a0;
          } else a0.clear();
          SpecificData.Array<java.lang.CharSequence> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.CharSequence>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              java.lang.CharSequence e0 = (ga0 != null ? ga0.peek() : null);
              e0 = in.readString(e0 instanceof Utf8 ? (Utf8)e0 : null);
              a0.add(e0);
            }
          }
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.type = null;
          } else {
            this.type = com.emi.events.catalog.OrderType.values()[in.readEnum()];
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










