--BOOKS
ALTER TABLE books
	ADD COLUMN totalChapters INT NOT NULL DEFAULT 0,
	ADD COLUMN status VARCHAR(50) NOT NULL DEFAULT 'PUBLIC',
	ADD COLUMN created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
	ADD COLUMN updated_at TIMESTAMPTZ  NOT NULL DEFAULT now();
	
--GENRE
ALTER TABLE book_contents
	ADD COLUMN created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
	ADD COLUMN updated_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    ADD COLUMN status VARCHAR(50) NOT NULL DEFAULT 'PUBLISHED',
    ADD COLUMN free_access BOOLEAN NOT NULL DEFAULT FALSE;