/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.emi.events;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class BookUpdatedEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6125206396878915573L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"BookUpdatedEvent\",\"namespace\":\"com.emi.events\",\"fields\":[{\"name\":\"bookId\",\"type\":\"string\"},{\"name\":\"title\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"description\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"price\",\"type\":[\"null\",\"double\"],\"default\":null},{\"name\":\"lifeCycleStatus\",\"type\":[\"null\",{\"type\":\"enum\",\"name\":\"BookLifeCycleStatus\",\"symbols\":[\"DRAFT\",\"ONGOING\",\"COMPLETED\"]}],\"default\":null},{\"name\":\"visibilityStatus\",\"type\":[\"null\",{\"type\":\"enum\",\"name\":\"BookVisibilityStatus\",\"symbols\":[\"PRIVATE\",\"PUBLIC\",\"DELETE\"]}],\"default\":null},{\"name\":\"freePreview\",\"type\":[\"null\",\"boolean\"],\"default\":null},{\"name\":\"updatedAt\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<BookUpdatedEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<BookUpdatedEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<BookUpdatedEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<BookUpdatedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<BookUpdatedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this BookUpdatedEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a BookUpdatedEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a BookUpdatedEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static BookUpdatedEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence bookId;
  private java.lang.CharSequence title;
  private java.lang.CharSequence description;
  private java.lang.Double price;
  private com.emi.events.BookLifeCycleStatus lifeCycleStatus;
  private com.emi.events.BookVisibilityStatus visibilityStatus;
  private java.lang.Boolean freePreview;
  private long updatedAt;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public BookUpdatedEvent() {}

  /**
   * All-args constructor.
   * @param bookId The new value for bookId
   * @param title The new value for title
   * @param description The new value for description
   * @param price The new value for price
   * @param lifeCycleStatus The new value for lifeCycleStatus
   * @param visibilityStatus The new value for visibilityStatus
   * @param freePreview The new value for freePreview
   * @param updatedAt The new value for updatedAt
   */
  public BookUpdatedEvent(java.lang.CharSequence bookId, java.lang.CharSequence title, java.lang.CharSequence description, java.lang.Double price, com.emi.events.BookLifeCycleStatus lifeCycleStatus, com.emi.events.BookVisibilityStatus visibilityStatus, java.lang.Boolean freePreview, java.lang.Long updatedAt) {
    this.bookId = bookId;
    this.title = title;
    this.description = description;
    this.price = price;
    this.lifeCycleStatus = lifeCycleStatus;
    this.visibilityStatus = visibilityStatus;
    this.freePreview = freePreview;
    this.updatedAt = updatedAt;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return bookId;
    case 1: return title;
    case 2: return description;
    case 3: return price;
    case 4: return lifeCycleStatus;
    case 5: return visibilityStatus;
    case 6: return freePreview;
    case 7: return updatedAt;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: bookId = (java.lang.CharSequence)value$; break;
    case 1: title = (java.lang.CharSequence)value$; break;
    case 2: description = (java.lang.CharSequence)value$; break;
    case 3: price = (java.lang.Double)value$; break;
    case 4: lifeCycleStatus = (com.emi.events.BookLifeCycleStatus)value$; break;
    case 5: visibilityStatus = (com.emi.events.BookVisibilityStatus)value$; break;
    case 6: freePreview = (java.lang.Boolean)value$; break;
    case 7: updatedAt = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'bookId' field.
   * @return The value of the 'bookId' field.
   */
  public java.lang.CharSequence getBookId() {
    return bookId;
  }


  /**
   * Sets the value of the 'bookId' field.
   * @param value the value to set.
   */
  public void setBookId(java.lang.CharSequence value) {
    this.bookId = value;
  }

  /**
   * Gets the value of the 'title' field.
   * @return The value of the 'title' field.
   */
  public java.lang.CharSequence getTitle() {
    return title;
  }


  /**
   * Sets the value of the 'title' field.
   * @param value the value to set.
   */
  public void setTitle(java.lang.CharSequence value) {
    this.title = value;
  }

  /**
   * Gets the value of the 'description' field.
   * @return The value of the 'description' field.
   */
  public java.lang.CharSequence getDescription() {
    return description;
  }


  /**
   * Sets the value of the 'description' field.
   * @param value the value to set.
   */
  public void setDescription(java.lang.CharSequence value) {
    this.description = value;
  }

  /**
   * Gets the value of the 'price' field.
   * @return The value of the 'price' field.
   */
  public java.lang.Double getPrice() {
    return price;
  }


  /**
   * Sets the value of the 'price' field.
   * @param value the value to set.
   */
  public void setPrice(java.lang.Double value) {
    this.price = value;
  }

  /**
   * Gets the value of the 'lifeCycleStatus' field.
   * @return The value of the 'lifeCycleStatus' field.
   */
  public com.emi.events.BookLifeCycleStatus getLifeCycleStatus() {
    return lifeCycleStatus;
  }


  /**
   * Sets the value of the 'lifeCycleStatus' field.
   * @param value the value to set.
   */
  public void setLifeCycleStatus(com.emi.events.BookLifeCycleStatus value) {
    this.lifeCycleStatus = value;
  }

  /**
   * Gets the value of the 'visibilityStatus' field.
   * @return The value of the 'visibilityStatus' field.
   */
  public com.emi.events.BookVisibilityStatus getVisibilityStatus() {
    return visibilityStatus;
  }


  /**
   * Sets the value of the 'visibilityStatus' field.
   * @param value the value to set.
   */
  public void setVisibilityStatus(com.emi.events.BookVisibilityStatus value) {
    this.visibilityStatus = value;
  }

  /**
   * Gets the value of the 'freePreview' field.
   * @return The value of the 'freePreview' field.
   */
  public java.lang.Boolean getFreePreview() {
    return freePreview;
  }


  /**
   * Sets the value of the 'freePreview' field.
   * @param value the value to set.
   */
  public void setFreePreview(java.lang.Boolean value) {
    this.freePreview = value;
  }

  /**
   * Gets the value of the 'updatedAt' field.
   * @return The value of the 'updatedAt' field.
   */
  public long getUpdatedAt() {
    return updatedAt;
  }


  /**
   * Sets the value of the 'updatedAt' field.
   * @param value the value to set.
   */
  public void setUpdatedAt(long value) {
    this.updatedAt = value;
  }

  /**
   * Creates a new BookUpdatedEvent RecordBuilder.
   * @return A new BookUpdatedEvent RecordBuilder
   */
  public static com.emi.events.BookUpdatedEvent.Builder newBuilder() {
    return new com.emi.events.BookUpdatedEvent.Builder();
  }

  /**
   * Creates a new BookUpdatedEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new BookUpdatedEvent RecordBuilder
   */
  public static com.emi.events.BookUpdatedEvent.Builder newBuilder(com.emi.events.BookUpdatedEvent.Builder other) {
    if (other == null) {
      return new com.emi.events.BookUpdatedEvent.Builder();
    } else {
      return new com.emi.events.BookUpdatedEvent.Builder(other);
    }
  }

  /**
   * Creates a new BookUpdatedEvent RecordBuilder by copying an existing BookUpdatedEvent instance.
   * @param other The existing instance to copy.
   * @return A new BookUpdatedEvent RecordBuilder
   */
  public static com.emi.events.BookUpdatedEvent.Builder newBuilder(com.emi.events.BookUpdatedEvent other) {
    if (other == null) {
      return new com.emi.events.BookUpdatedEvent.Builder();
    } else {
      return new com.emi.events.BookUpdatedEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for BookUpdatedEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<BookUpdatedEvent>
    implements org.apache.avro.data.RecordBuilder<BookUpdatedEvent> {

    private java.lang.CharSequence bookId;
    private java.lang.CharSequence title;
    private java.lang.CharSequence description;
    private java.lang.Double price;
    private com.emi.events.BookLifeCycleStatus lifeCycleStatus;
    private com.emi.events.BookVisibilityStatus visibilityStatus;
    private java.lang.Boolean freePreview;
    private long updatedAt;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.emi.events.BookUpdatedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.bookId)) {
        this.bookId = data().deepCopy(fields()[0].schema(), other.bookId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.title)) {
        this.title = data().deepCopy(fields()[1].schema(), other.title);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.description)) {
        this.description = data().deepCopy(fields()[2].schema(), other.description);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.price)) {
        this.price = data().deepCopy(fields()[3].schema(), other.price);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.lifeCycleStatus)) {
        this.lifeCycleStatus = data().deepCopy(fields()[4].schema(), other.lifeCycleStatus);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.visibilityStatus)) {
        this.visibilityStatus = data().deepCopy(fields()[5].schema(), other.visibilityStatus);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.freePreview)) {
        this.freePreview = data().deepCopy(fields()[6].schema(), other.freePreview);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.updatedAt)) {
        this.updatedAt = data().deepCopy(fields()[7].schema(), other.updatedAt);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
    }

    /**
     * Creates a Builder by copying an existing BookUpdatedEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.emi.events.BookUpdatedEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.bookId)) {
        this.bookId = data().deepCopy(fields()[0].schema(), other.bookId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.title)) {
        this.title = data().deepCopy(fields()[1].schema(), other.title);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.description)) {
        this.description = data().deepCopy(fields()[2].schema(), other.description);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.price)) {
        this.price = data().deepCopy(fields()[3].schema(), other.price);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.lifeCycleStatus)) {
        this.lifeCycleStatus = data().deepCopy(fields()[4].schema(), other.lifeCycleStatus);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.visibilityStatus)) {
        this.visibilityStatus = data().deepCopy(fields()[5].schema(), other.visibilityStatus);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.freePreview)) {
        this.freePreview = data().deepCopy(fields()[6].schema(), other.freePreview);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.updatedAt)) {
        this.updatedAt = data().deepCopy(fields()[7].schema(), other.updatedAt);
        fieldSetFlags()[7] = true;
      }
    }

    /**
      * Gets the value of the 'bookId' field.
      * @return The value.
      */
    public java.lang.CharSequence getBookId() {
      return bookId;
    }


    /**
      * Sets the value of the 'bookId' field.
      * @param value The value of 'bookId'.
      * @return This builder.
      */
    public com.emi.events.BookUpdatedEvent.Builder setBookId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.bookId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'bookId' field has been set.
      * @return True if the 'bookId' field has been set, false otherwise.
      */
    public boolean hasBookId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'bookId' field.
      * @return This builder.
      */
    public com.emi.events.BookUpdatedEvent.Builder clearBookId() {
      bookId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'title' field.
      * @return The value.
      */
    public java.lang.CharSequence getTitle() {
      return title;
    }


    /**
      * Sets the value of the 'title' field.
      * @param value The value of 'title'.
      * @return This builder.
      */
    public com.emi.events.BookUpdatedEvent.Builder setTitle(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.title = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'title' field has been set.
      * @return True if the 'title' field has been set, false otherwise.
      */
    public boolean hasTitle() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'title' field.
      * @return This builder.
      */
    public com.emi.events.BookUpdatedEvent.Builder clearTitle() {
      title = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'description' field.
      * @return The value.
      */
    public java.lang.CharSequence getDescription() {
      return description;
    }


    /**
      * Sets the value of the 'description' field.
      * @param value The value of 'description'.
      * @return This builder.
      */
    public com.emi.events.BookUpdatedEvent.Builder setDescription(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.description = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'description' field has been set.
      * @return True if the 'description' field has been set, false otherwise.
      */
    public boolean hasDescription() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'description' field.
      * @return This builder.
      */
    public com.emi.events.BookUpdatedEvent.Builder clearDescription() {
      description = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'price' field.
      * @return The value.
      */
    public java.lang.Double getPrice() {
      return price;
    }


    /**
      * Sets the value of the 'price' field.
      * @param value The value of 'price'.
      * @return This builder.
      */
    public com.emi.events.BookUpdatedEvent.Builder setPrice(java.lang.Double value) {
      validate(fields()[3], value);
      this.price = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'price' field has been set.
      * @return True if the 'price' field has been set, false otherwise.
      */
    public boolean hasPrice() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'price' field.
      * @return This builder.
      */
    public com.emi.events.BookUpdatedEvent.Builder clearPrice() {
      price = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'lifeCycleStatus' field.
      * @return The value.
      */
    public com.emi.events.BookLifeCycleStatus getLifeCycleStatus() {
      return lifeCycleStatus;
    }


    /**
      * Sets the value of the 'lifeCycleStatus' field.
      * @param value The value of 'lifeCycleStatus'.
      * @return This builder.
      */
    public com.emi.events.BookUpdatedEvent.Builder setLifeCycleStatus(com.emi.events.BookLifeCycleStatus value) {
      validate(fields()[4], value);
      this.lifeCycleStatus = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'lifeCycleStatus' field has been set.
      * @return True if the 'lifeCycleStatus' field has been set, false otherwise.
      */
    public boolean hasLifeCycleStatus() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'lifeCycleStatus' field.
      * @return This builder.
      */
    public com.emi.events.BookUpdatedEvent.Builder clearLifeCycleStatus() {
      lifeCycleStatus = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'visibilityStatus' field.
      * @return The value.
      */
    public com.emi.events.BookVisibilityStatus getVisibilityStatus() {
      return visibilityStatus;
    }


    /**
      * Sets the value of the 'visibilityStatus' field.
      * @param value The value of 'visibilityStatus'.
      * @return This builder.
      */
    public com.emi.events.BookUpdatedEvent.Builder setVisibilityStatus(com.emi.events.BookVisibilityStatus value) {
      validate(fields()[5], value);
      this.visibilityStatus = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'visibilityStatus' field has been set.
      * @return True if the 'visibilityStatus' field has been set, false otherwise.
      */
    public boolean hasVisibilityStatus() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'visibilityStatus' field.
      * @return This builder.
      */
    public com.emi.events.BookUpdatedEvent.Builder clearVisibilityStatus() {
      visibilityStatus = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'freePreview' field.
      * @return The value.
      */
    public java.lang.Boolean getFreePreview() {
      return freePreview;
    }


    /**
      * Sets the value of the 'freePreview' field.
      * @param value The value of 'freePreview'.
      * @return This builder.
      */
    public com.emi.events.BookUpdatedEvent.Builder setFreePreview(java.lang.Boolean value) {
      validate(fields()[6], value);
      this.freePreview = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'freePreview' field has been set.
      * @return True if the 'freePreview' field has been set, false otherwise.
      */
    public boolean hasFreePreview() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'freePreview' field.
      * @return This builder.
      */
    public com.emi.events.BookUpdatedEvent.Builder clearFreePreview() {
      freePreview = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'updatedAt' field.
      * @return The value.
      */
    public long getUpdatedAt() {
      return updatedAt;
    }


    /**
      * Sets the value of the 'updatedAt' field.
      * @param value The value of 'updatedAt'.
      * @return This builder.
      */
    public com.emi.events.BookUpdatedEvent.Builder setUpdatedAt(long value) {
      validate(fields()[7], value);
      this.updatedAt = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'updatedAt' field has been set.
      * @return True if the 'updatedAt' field has been set, false otherwise.
      */
    public boolean hasUpdatedAt() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'updatedAt' field.
      * @return This builder.
      */
    public com.emi.events.BookUpdatedEvent.Builder clearUpdatedAt() {
      fieldSetFlags()[7] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public BookUpdatedEvent build() {
      try {
        BookUpdatedEvent record = new BookUpdatedEvent();
        record.bookId = fieldSetFlags()[0] ? this.bookId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.title = fieldSetFlags()[1] ? this.title : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.description = fieldSetFlags()[2] ? this.description : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.price = fieldSetFlags()[3] ? this.price : (java.lang.Double) defaultValue(fields()[3]);
        record.lifeCycleStatus = fieldSetFlags()[4] ? this.lifeCycleStatus : (com.emi.events.BookLifeCycleStatus) defaultValue(fields()[4]);
        record.visibilityStatus = fieldSetFlags()[5] ? this.visibilityStatus : (com.emi.events.BookVisibilityStatus) defaultValue(fields()[5]);
        record.freePreview = fieldSetFlags()[6] ? this.freePreview : (java.lang.Boolean) defaultValue(fields()[6]);
        record.updatedAt = fieldSetFlags()[7] ? this.updatedAt : (java.lang.Long) defaultValue(fields()[7]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<BookUpdatedEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<BookUpdatedEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<BookUpdatedEvent>
    READER$ = (org.apache.avro.io.DatumReader<BookUpdatedEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.bookId);

    if (this.title == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.title);
    }

    if (this.description == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.description);
    }

    if (this.price == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeDouble(this.price);
    }

    if (this.lifeCycleStatus == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeEnum(this.lifeCycleStatus.ordinal());
    }

    if (this.visibilityStatus == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeEnum(this.visibilityStatus.ordinal());
    }

    if (this.freePreview == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeBoolean(this.freePreview);
    }

    out.writeLong(this.updatedAt);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.bookId = in.readString(this.bookId instanceof Utf8 ? (Utf8)this.bookId : null);

      if (in.readIndex() != 1) {
        in.readNull();
        this.title = null;
      } else {
        this.title = in.readString(this.title instanceof Utf8 ? (Utf8)this.title : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.description = null;
      } else {
        this.description = in.readString(this.description instanceof Utf8 ? (Utf8)this.description : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.price = null;
      } else {
        this.price = in.readDouble();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.lifeCycleStatus = null;
      } else {
        this.lifeCycleStatus = com.emi.events.BookLifeCycleStatus.values()[in.readEnum()];
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.visibilityStatus = null;
      } else {
        this.visibilityStatus = com.emi.events.BookVisibilityStatus.values()[in.readEnum()];
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.freePreview = null;
      } else {
        this.freePreview = in.readBoolean();
      }

      this.updatedAt = in.readLong();

    } else {
      for (int i = 0; i < 8; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.bookId = in.readString(this.bookId instanceof Utf8 ? (Utf8)this.bookId : null);
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.title = null;
          } else {
            this.title = in.readString(this.title instanceof Utf8 ? (Utf8)this.title : null);
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.description = null;
          } else {
            this.description = in.readString(this.description instanceof Utf8 ? (Utf8)this.description : null);
          }
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.price = null;
          } else {
            this.price = in.readDouble();
          }
          break;

        case 4:
          if (in.readIndex() != 1) {
            in.readNull();
            this.lifeCycleStatus = null;
          } else {
            this.lifeCycleStatus = com.emi.events.BookLifeCycleStatus.values()[in.readEnum()];
          }
          break;

        case 5:
          if (in.readIndex() != 1) {
            in.readNull();
            this.visibilityStatus = null;
          } else {
            this.visibilityStatus = com.emi.events.BookVisibilityStatus.values()[in.readEnum()];
          }
          break;

        case 6:
          if (in.readIndex() != 1) {
            in.readNull();
            this.freePreview = null;
          } else {
            this.freePreview = in.readBoolean();
          }
          break;

        case 7:
          this.updatedAt = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










