/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.emi.events;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class BookDeletedEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7170911526727216048L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"BookDeletedEvent\",\"namespace\":\"com.emi.events\",\"fields\":[{\"name\":\"bookId\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<BookDeletedEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<BookDeletedEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<BookDeletedEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<BookDeletedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<BookDeletedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this BookDeletedEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a BookDeletedEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a BookDeletedEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static BookDeletedEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence bookId;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public BookDeletedEvent() {}

  /**
   * All-args constructor.
   * @param bookId The new value for bookId
   */
  public BookDeletedEvent(java.lang.CharSequence bookId) {
    this.bookId = bookId;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return bookId;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: bookId = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'bookId' field.
   * @return The value of the 'bookId' field.
   */
  public java.lang.CharSequence getBookId() {
    return bookId;
  }


  /**
   * Sets the value of the 'bookId' field.
   * @param value the value to set.
   */
  public void setBookId(java.lang.CharSequence value) {
    this.bookId = value;
  }

  /**
   * Creates a new BookDeletedEvent RecordBuilder.
   * @return A new BookDeletedEvent RecordBuilder
   */
  public static com.emi.events.BookDeletedEvent.Builder newBuilder() {
    return new com.emi.events.BookDeletedEvent.Builder();
  }

  /**
   * Creates a new BookDeletedEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new BookDeletedEvent RecordBuilder
   */
  public static com.emi.events.BookDeletedEvent.Builder newBuilder(com.emi.events.BookDeletedEvent.Builder other) {
    if (other == null) {
      return new com.emi.events.BookDeletedEvent.Builder();
    } else {
      return new com.emi.events.BookDeletedEvent.Builder(other);
    }
  }

  /**
   * Creates a new BookDeletedEvent RecordBuilder by copying an existing BookDeletedEvent instance.
   * @param other The existing instance to copy.
   * @return A new BookDeletedEvent RecordBuilder
   */
  public static com.emi.events.BookDeletedEvent.Builder newBuilder(com.emi.events.BookDeletedEvent other) {
    if (other == null) {
      return new com.emi.events.BookDeletedEvent.Builder();
    } else {
      return new com.emi.events.BookDeletedEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for BookDeletedEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<BookDeletedEvent>
    implements org.apache.avro.data.RecordBuilder<BookDeletedEvent> {

    private java.lang.CharSequence bookId;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.emi.events.BookDeletedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.bookId)) {
        this.bookId = data().deepCopy(fields()[0].schema(), other.bookId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing BookDeletedEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.emi.events.BookDeletedEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.bookId)) {
        this.bookId = data().deepCopy(fields()[0].schema(), other.bookId);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'bookId' field.
      * @return The value.
      */
    public java.lang.CharSequence getBookId() {
      return bookId;
    }


    /**
      * Sets the value of the 'bookId' field.
      * @param value The value of 'bookId'.
      * @return This builder.
      */
    public com.emi.events.BookDeletedEvent.Builder setBookId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.bookId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'bookId' field has been set.
      * @return True if the 'bookId' field has been set, false otherwise.
      */
    public boolean hasBookId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'bookId' field.
      * @return This builder.
      */
    public com.emi.events.BookDeletedEvent.Builder clearBookId() {
      bookId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public BookDeletedEvent build() {
      try {
        BookDeletedEvent record = new BookDeletedEvent();
        record.bookId = fieldSetFlags()[0] ? this.bookId : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<BookDeletedEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<BookDeletedEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<BookDeletedEvent>
    READER$ = (org.apache.avro.io.DatumReader<BookDeletedEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.bookId);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.bookId = in.readString(this.bookId instanceof Utf8 ? (Utf8)this.bookId : null);

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.bookId = in.readString(this.bookId instanceof Utf8 ? (Utf8)this.bookId : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










