/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.emi.events.bookPublished;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class BookPublishedEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1678021546606132609L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"BookPublishedEvent\",\"namespace\":\"com.emi.events.bookPublished\",\"fields\":[{\"name\":\"bookId\",\"type\":\"string\"},{\"name\":\"title\",\"type\":\"string\"},{\"name\":\"description\",\"type\":\"string\"},{\"name\":\"price\",\"type\":\"double\"},{\"name\":\"authorNames\",\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"genres\",\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"freePreviewAvailable\",\"type\":\"boolean\"},{\"name\":\"lifeCycleStatus\",\"type\":{\"type\":\"enum\",\"name\":\"BookLifeCycleStatus\",\"symbols\":[\"DRAFT\",\"ONGOING\",\"COMPLETED\"]}},{\"name\":\"visibilityStatus\",\"type\":[\"null\",{\"type\":\"enum\",\"name\":\"BookVisibilityStatus\",\"symbols\":[\"PRIVATE\",\"PUBLIC\",\"DELETE\"]}],\"default\":null},{\"name\":\"publishedAt\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<BookPublishedEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<BookPublishedEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<BookPublishedEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<BookPublishedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<BookPublishedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this BookPublishedEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a BookPublishedEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a BookPublishedEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static BookPublishedEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence bookId;
  private java.lang.CharSequence title;
  private java.lang.CharSequence description;
  private double price;
  private java.util.List<java.lang.CharSequence> authorNames;
  private java.util.List<java.lang.CharSequence> genres;
  private boolean freePreviewAvailable;
  private com.emi.events.bookPublished.BookLifeCycleStatus lifeCycleStatus;
  private com.emi.events.bookPublished.BookVisibilityStatus visibilityStatus;
  private long publishedAt;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public BookPublishedEvent() {}

  /**
   * All-args constructor.
   * @param bookId The new value for bookId
   * @param title The new value for title
   * @param description The new value for description
   * @param price The new value for price
   * @param authorNames The new value for authorNames
   * @param genres The new value for genres
   * @param freePreviewAvailable The new value for freePreviewAvailable
   * @param lifeCycleStatus The new value for lifeCycleStatus
   * @param visibilityStatus The new value for visibilityStatus
   * @param publishedAt The new value for publishedAt
   */
  public BookPublishedEvent(java.lang.CharSequence bookId, java.lang.CharSequence title, java.lang.CharSequence description, java.lang.Double price, java.util.List<java.lang.CharSequence> authorNames, java.util.List<java.lang.CharSequence> genres, java.lang.Boolean freePreviewAvailable, com.emi.events.bookPublished.BookLifeCycleStatus lifeCycleStatus, com.emi.events.bookPublished.BookVisibilityStatus visibilityStatus, java.lang.Long publishedAt) {
    this.bookId = bookId;
    this.title = title;
    this.description = description;
    this.price = price;
    this.authorNames = authorNames;
    this.genres = genres;
    this.freePreviewAvailable = freePreviewAvailable;
    this.lifeCycleStatus = lifeCycleStatus;
    this.visibilityStatus = visibilityStatus;
    this.publishedAt = publishedAt;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return bookId;
    case 1: return title;
    case 2: return description;
    case 3: return price;
    case 4: return authorNames;
    case 5: return genres;
    case 6: return freePreviewAvailable;
    case 7: return lifeCycleStatus;
    case 8: return visibilityStatus;
    case 9: return publishedAt;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: bookId = (java.lang.CharSequence)value$; break;
    case 1: title = (java.lang.CharSequence)value$; break;
    case 2: description = (java.lang.CharSequence)value$; break;
    case 3: price = (java.lang.Double)value$; break;
    case 4: authorNames = (java.util.List<java.lang.CharSequence>)value$; break;
    case 5: genres = (java.util.List<java.lang.CharSequence>)value$; break;
    case 6: freePreviewAvailable = (java.lang.Boolean)value$; break;
    case 7: lifeCycleStatus = (com.emi.events.bookPublished.BookLifeCycleStatus)value$; break;
    case 8: visibilityStatus = (com.emi.events.bookPublished.BookVisibilityStatus)value$; break;
    case 9: publishedAt = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'bookId' field.
   * @return The value of the 'bookId' field.
   */
  public java.lang.CharSequence getBookId() {
    return bookId;
  }


  /**
   * Sets the value of the 'bookId' field.
   * @param value the value to set.
   */
  public void setBookId(java.lang.CharSequence value) {
    this.bookId = value;
  }

  /**
   * Gets the value of the 'title' field.
   * @return The value of the 'title' field.
   */
  public java.lang.CharSequence getTitle() {
    return title;
  }


  /**
   * Sets the value of the 'title' field.
   * @param value the value to set.
   */
  public void setTitle(java.lang.CharSequence value) {
    this.title = value;
  }

  /**
   * Gets the value of the 'description' field.
   * @return The value of the 'description' field.
   */
  public java.lang.CharSequence getDescription() {
    return description;
  }


  /**
   * Sets the value of the 'description' field.
   * @param value the value to set.
   */
  public void setDescription(java.lang.CharSequence value) {
    this.description = value;
  }

  /**
   * Gets the value of the 'price' field.
   * @return The value of the 'price' field.
   */
  public double getPrice() {
    return price;
  }


  /**
   * Sets the value of the 'price' field.
   * @param value the value to set.
   */
  public void setPrice(double value) {
    this.price = value;
  }

  /**
   * Gets the value of the 'authorNames' field.
   * @return The value of the 'authorNames' field.
   */
  public java.util.List<java.lang.CharSequence> getAuthorNames() {
    return authorNames;
  }


  /**
   * Sets the value of the 'authorNames' field.
   * @param value the value to set.
   */
  public void setAuthorNames(java.util.List<java.lang.CharSequence> value) {
    this.authorNames = value;
  }

  /**
   * Gets the value of the 'genres' field.
   * @return The value of the 'genres' field.
   */
  public java.util.List<java.lang.CharSequence> getGenres() {
    return genres;
  }


  /**
   * Sets the value of the 'genres' field.
   * @param value the value to set.
   */
  public void setGenres(java.util.List<java.lang.CharSequence> value) {
    this.genres = value;
  }

  /**
   * Gets the value of the 'freePreviewAvailable' field.
   * @return The value of the 'freePreviewAvailable' field.
   */
  public boolean getFreePreviewAvailable() {
    return freePreviewAvailable;
  }


  /**
   * Sets the value of the 'freePreviewAvailable' field.
   * @param value the value to set.
   */
  public void setFreePreviewAvailable(boolean value) {
    this.freePreviewAvailable = value;
  }

  /**
   * Gets the value of the 'lifeCycleStatus' field.
   * @return The value of the 'lifeCycleStatus' field.
   */
  public com.emi.events.bookPublished.BookLifeCycleStatus getLifeCycleStatus() {
    return lifeCycleStatus;
  }


  /**
   * Sets the value of the 'lifeCycleStatus' field.
   * @param value the value to set.
   */
  public void setLifeCycleStatus(com.emi.events.bookPublished.BookLifeCycleStatus value) {
    this.lifeCycleStatus = value;
  }

  /**
   * Gets the value of the 'visibilityStatus' field.
   * @return The value of the 'visibilityStatus' field.
   */
  public com.emi.events.bookPublished.BookVisibilityStatus getVisibilityStatus() {
    return visibilityStatus;
  }


  /**
   * Sets the value of the 'visibilityStatus' field.
   * @param value the value to set.
   */
  public void setVisibilityStatus(com.emi.events.bookPublished.BookVisibilityStatus value) {
    this.visibilityStatus = value;
  }

  /**
   * Gets the value of the 'publishedAt' field.
   * @return The value of the 'publishedAt' field.
   */
  public long getPublishedAt() {
    return publishedAt;
  }


  /**
   * Sets the value of the 'publishedAt' field.
   * @param value the value to set.
   */
  public void setPublishedAt(long value) {
    this.publishedAt = value;
  }

  /**
   * Creates a new BookPublishedEvent RecordBuilder.
   * @return A new BookPublishedEvent RecordBuilder
   */
  public static com.emi.events.bookPublished.BookPublishedEvent.Builder newBuilder() {
    return new com.emi.events.bookPublished.BookPublishedEvent.Builder();
  }

  /**
   * Creates a new BookPublishedEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new BookPublishedEvent RecordBuilder
   */
  public static com.emi.events.bookPublished.BookPublishedEvent.Builder newBuilder(com.emi.events.bookPublished.BookPublishedEvent.Builder other) {
    if (other == null) {
      return new com.emi.events.bookPublished.BookPublishedEvent.Builder();
    } else {
      return new com.emi.events.bookPublished.BookPublishedEvent.Builder(other);
    }
  }

  /**
   * Creates a new BookPublishedEvent RecordBuilder by copying an existing BookPublishedEvent instance.
   * @param other The existing instance to copy.
   * @return A new BookPublishedEvent RecordBuilder
   */
  public static com.emi.events.bookPublished.BookPublishedEvent.Builder newBuilder(com.emi.events.bookPublished.BookPublishedEvent other) {
    if (other == null) {
      return new com.emi.events.bookPublished.BookPublishedEvent.Builder();
    } else {
      return new com.emi.events.bookPublished.BookPublishedEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for BookPublishedEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<BookPublishedEvent>
    implements org.apache.avro.data.RecordBuilder<BookPublishedEvent> {

    private java.lang.CharSequence bookId;
    private java.lang.CharSequence title;
    private java.lang.CharSequence description;
    private double price;
    private java.util.List<java.lang.CharSequence> authorNames;
    private java.util.List<java.lang.CharSequence> genres;
    private boolean freePreviewAvailable;
    private com.emi.events.bookPublished.BookLifeCycleStatus lifeCycleStatus;
    private com.emi.events.bookPublished.BookVisibilityStatus visibilityStatus;
    private long publishedAt;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.emi.events.bookPublished.BookPublishedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.bookId)) {
        this.bookId = data().deepCopy(fields()[0].schema(), other.bookId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.title)) {
        this.title = data().deepCopy(fields()[1].schema(), other.title);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.description)) {
        this.description = data().deepCopy(fields()[2].schema(), other.description);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.price)) {
        this.price = data().deepCopy(fields()[3].schema(), other.price);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.authorNames)) {
        this.authorNames = data().deepCopy(fields()[4].schema(), other.authorNames);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.genres)) {
        this.genres = data().deepCopy(fields()[5].schema(), other.genres);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.freePreviewAvailable)) {
        this.freePreviewAvailable = data().deepCopy(fields()[6].schema(), other.freePreviewAvailable);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.lifeCycleStatus)) {
        this.lifeCycleStatus = data().deepCopy(fields()[7].schema(), other.lifeCycleStatus);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.visibilityStatus)) {
        this.visibilityStatus = data().deepCopy(fields()[8].schema(), other.visibilityStatus);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.publishedAt)) {
        this.publishedAt = data().deepCopy(fields()[9].schema(), other.publishedAt);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
    }

    /**
     * Creates a Builder by copying an existing BookPublishedEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.emi.events.bookPublished.BookPublishedEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.bookId)) {
        this.bookId = data().deepCopy(fields()[0].schema(), other.bookId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.title)) {
        this.title = data().deepCopy(fields()[1].schema(), other.title);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.description)) {
        this.description = data().deepCopy(fields()[2].schema(), other.description);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.price)) {
        this.price = data().deepCopy(fields()[3].schema(), other.price);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.authorNames)) {
        this.authorNames = data().deepCopy(fields()[4].schema(), other.authorNames);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.genres)) {
        this.genres = data().deepCopy(fields()[5].schema(), other.genres);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.freePreviewAvailable)) {
        this.freePreviewAvailable = data().deepCopy(fields()[6].schema(), other.freePreviewAvailable);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.lifeCycleStatus)) {
        this.lifeCycleStatus = data().deepCopy(fields()[7].schema(), other.lifeCycleStatus);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.visibilityStatus)) {
        this.visibilityStatus = data().deepCopy(fields()[8].schema(), other.visibilityStatus);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.publishedAt)) {
        this.publishedAt = data().deepCopy(fields()[9].schema(), other.publishedAt);
        fieldSetFlags()[9] = true;
      }
    }

    /**
      * Gets the value of the 'bookId' field.
      * @return The value.
      */
    public java.lang.CharSequence getBookId() {
      return bookId;
    }


    /**
      * Sets the value of the 'bookId' field.
      * @param value The value of 'bookId'.
      * @return This builder.
      */
    public com.emi.events.bookPublished.BookPublishedEvent.Builder setBookId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.bookId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'bookId' field has been set.
      * @return True if the 'bookId' field has been set, false otherwise.
      */
    public boolean hasBookId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'bookId' field.
      * @return This builder.
      */
    public com.emi.events.bookPublished.BookPublishedEvent.Builder clearBookId() {
      bookId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'title' field.
      * @return The value.
      */
    public java.lang.CharSequence getTitle() {
      return title;
    }


    /**
      * Sets the value of the 'title' field.
      * @param value The value of 'title'.
      * @return This builder.
      */
    public com.emi.events.bookPublished.BookPublishedEvent.Builder setTitle(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.title = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'title' field has been set.
      * @return True if the 'title' field has been set, false otherwise.
      */
    public boolean hasTitle() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'title' field.
      * @return This builder.
      */
    public com.emi.events.bookPublished.BookPublishedEvent.Builder clearTitle() {
      title = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'description' field.
      * @return The value.
      */
    public java.lang.CharSequence getDescription() {
      return description;
    }


    /**
      * Sets the value of the 'description' field.
      * @param value The value of 'description'.
      * @return This builder.
      */
    public com.emi.events.bookPublished.BookPublishedEvent.Builder setDescription(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.description = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'description' field has been set.
      * @return True if the 'description' field has been set, false otherwise.
      */
    public boolean hasDescription() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'description' field.
      * @return This builder.
      */
    public com.emi.events.bookPublished.BookPublishedEvent.Builder clearDescription() {
      description = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'price' field.
      * @return The value.
      */
    public double getPrice() {
      return price;
    }


    /**
      * Sets the value of the 'price' field.
      * @param value The value of 'price'.
      * @return This builder.
      */
    public com.emi.events.bookPublished.BookPublishedEvent.Builder setPrice(double value) {
      validate(fields()[3], value);
      this.price = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'price' field has been set.
      * @return True if the 'price' field has been set, false otherwise.
      */
    public boolean hasPrice() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'price' field.
      * @return This builder.
      */
    public com.emi.events.bookPublished.BookPublishedEvent.Builder clearPrice() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'authorNames' field.
      * @return The value.
      */
    public java.util.List<java.lang.CharSequence> getAuthorNames() {
      return authorNames;
    }


    /**
      * Sets the value of the 'authorNames' field.
      * @param value The value of 'authorNames'.
      * @return This builder.
      */
    public com.emi.events.bookPublished.BookPublishedEvent.Builder setAuthorNames(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[4], value);
      this.authorNames = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'authorNames' field has been set.
      * @return True if the 'authorNames' field has been set, false otherwise.
      */
    public boolean hasAuthorNames() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'authorNames' field.
      * @return This builder.
      */
    public com.emi.events.bookPublished.BookPublishedEvent.Builder clearAuthorNames() {
      authorNames = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'genres' field.
      * @return The value.
      */
    public java.util.List<java.lang.CharSequence> getGenres() {
      return genres;
    }


    /**
      * Sets the value of the 'genres' field.
      * @param value The value of 'genres'.
      * @return This builder.
      */
    public com.emi.events.bookPublished.BookPublishedEvent.Builder setGenres(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[5], value);
      this.genres = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'genres' field has been set.
      * @return True if the 'genres' field has been set, false otherwise.
      */
    public boolean hasGenres() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'genres' field.
      * @return This builder.
      */
    public com.emi.events.bookPublished.BookPublishedEvent.Builder clearGenres() {
      genres = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'freePreviewAvailable' field.
      * @return The value.
      */
    public boolean getFreePreviewAvailable() {
      return freePreviewAvailable;
    }


    /**
      * Sets the value of the 'freePreviewAvailable' field.
      * @param value The value of 'freePreviewAvailable'.
      * @return This builder.
      */
    public com.emi.events.bookPublished.BookPublishedEvent.Builder setFreePreviewAvailable(boolean value) {
      validate(fields()[6], value);
      this.freePreviewAvailable = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'freePreviewAvailable' field has been set.
      * @return True if the 'freePreviewAvailable' field has been set, false otherwise.
      */
    public boolean hasFreePreviewAvailable() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'freePreviewAvailable' field.
      * @return This builder.
      */
    public com.emi.events.bookPublished.BookPublishedEvent.Builder clearFreePreviewAvailable() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'lifeCycleStatus' field.
      * @return The value.
      */
    public com.emi.events.bookPublished.BookLifeCycleStatus getLifeCycleStatus() {
      return lifeCycleStatus;
    }


    /**
      * Sets the value of the 'lifeCycleStatus' field.
      * @param value The value of 'lifeCycleStatus'.
      * @return This builder.
      */
    public com.emi.events.bookPublished.BookPublishedEvent.Builder setLifeCycleStatus(com.emi.events.bookPublished.BookLifeCycleStatus value) {
      validate(fields()[7], value);
      this.lifeCycleStatus = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'lifeCycleStatus' field has been set.
      * @return True if the 'lifeCycleStatus' field has been set, false otherwise.
      */
    public boolean hasLifeCycleStatus() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'lifeCycleStatus' field.
      * @return This builder.
      */
    public com.emi.events.bookPublished.BookPublishedEvent.Builder clearLifeCycleStatus() {
      lifeCycleStatus = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'visibilityStatus' field.
      * @return The value.
      */
    public com.emi.events.bookPublished.BookVisibilityStatus getVisibilityStatus() {
      return visibilityStatus;
    }


    /**
      * Sets the value of the 'visibilityStatus' field.
      * @param value The value of 'visibilityStatus'.
      * @return This builder.
      */
    public com.emi.events.bookPublished.BookPublishedEvent.Builder setVisibilityStatus(com.emi.events.bookPublished.BookVisibilityStatus value) {
      validate(fields()[8], value);
      this.visibilityStatus = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'visibilityStatus' field has been set.
      * @return True if the 'visibilityStatus' field has been set, false otherwise.
      */
    public boolean hasVisibilityStatus() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'visibilityStatus' field.
      * @return This builder.
      */
    public com.emi.events.bookPublished.BookPublishedEvent.Builder clearVisibilityStatus() {
      visibilityStatus = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'publishedAt' field.
      * @return The value.
      */
    public long getPublishedAt() {
      return publishedAt;
    }


    /**
      * Sets the value of the 'publishedAt' field.
      * @param value The value of 'publishedAt'.
      * @return This builder.
      */
    public com.emi.events.bookPublished.BookPublishedEvent.Builder setPublishedAt(long value) {
      validate(fields()[9], value);
      this.publishedAt = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'publishedAt' field has been set.
      * @return True if the 'publishedAt' field has been set, false otherwise.
      */
    public boolean hasPublishedAt() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'publishedAt' field.
      * @return This builder.
      */
    public com.emi.events.bookPublished.BookPublishedEvent.Builder clearPublishedAt() {
      fieldSetFlags()[9] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public BookPublishedEvent build() {
      try {
        BookPublishedEvent record = new BookPublishedEvent();
        record.bookId = fieldSetFlags()[0] ? this.bookId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.title = fieldSetFlags()[1] ? this.title : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.description = fieldSetFlags()[2] ? this.description : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.price = fieldSetFlags()[3] ? this.price : (java.lang.Double) defaultValue(fields()[3]);
        record.authorNames = fieldSetFlags()[4] ? this.authorNames : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[4]);
        record.genres = fieldSetFlags()[5] ? this.genres : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[5]);
        record.freePreviewAvailable = fieldSetFlags()[6] ? this.freePreviewAvailable : (java.lang.Boolean) defaultValue(fields()[6]);
        record.lifeCycleStatus = fieldSetFlags()[7] ? this.lifeCycleStatus : (com.emi.events.bookPublished.BookLifeCycleStatus) defaultValue(fields()[7]);
        record.visibilityStatus = fieldSetFlags()[8] ? this.visibilityStatus : (com.emi.events.bookPublished.BookVisibilityStatus) defaultValue(fields()[8]);
        record.publishedAt = fieldSetFlags()[9] ? this.publishedAt : (java.lang.Long) defaultValue(fields()[9]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<BookPublishedEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<BookPublishedEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<BookPublishedEvent>
    READER$ = (org.apache.avro.io.DatumReader<BookPublishedEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.bookId);

    out.writeString(this.title);

    out.writeString(this.description);

    out.writeDouble(this.price);

    long size0 = this.authorNames.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (java.lang.CharSequence e0: this.authorNames) {
      actualSize0++;
      out.startItem();
      out.writeString(e0);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

    long size1 = this.genres.size();
    out.writeArrayStart();
    out.setItemCount(size1);
    long actualSize1 = 0;
    for (java.lang.CharSequence e1: this.genres) {
      actualSize1++;
      out.startItem();
      out.writeString(e1);
    }
    out.writeArrayEnd();
    if (actualSize1 != size1)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size1 + ", but element count was " + actualSize1 + ".");

    out.writeBoolean(this.freePreviewAvailable);

    out.writeEnum(this.lifeCycleStatus.ordinal());

    if (this.visibilityStatus == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeEnum(this.visibilityStatus.ordinal());
    }

    out.writeLong(this.publishedAt);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.bookId = in.readString(this.bookId instanceof Utf8 ? (Utf8)this.bookId : null);

      this.title = in.readString(this.title instanceof Utf8 ? (Utf8)this.title : null);

      this.description = in.readString(this.description instanceof Utf8 ? (Utf8)this.description : null);

      this.price = in.readDouble();

      long size0 = in.readArrayStart();
      java.util.List<java.lang.CharSequence> a0 = this.authorNames;
      if (a0 == null) {
        a0 = new SpecificData.Array<java.lang.CharSequence>((int)size0, SCHEMA$.getField("authorNames").schema());
        this.authorNames = a0;
      } else a0.clear();
      SpecificData.Array<java.lang.CharSequence> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.CharSequence>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          java.lang.CharSequence e0 = (ga0 != null ? ga0.peek() : null);
          e0 = in.readString(e0 instanceof Utf8 ? (Utf8)e0 : null);
          a0.add(e0);
        }
      }

      long size1 = in.readArrayStart();
      java.util.List<java.lang.CharSequence> a1 = this.genres;
      if (a1 == null) {
        a1 = new SpecificData.Array<java.lang.CharSequence>((int)size1, SCHEMA$.getField("genres").schema());
        this.genres = a1;
      } else a1.clear();
      SpecificData.Array<java.lang.CharSequence> ga1 = (a1 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.CharSequence>)a1 : null);
      for ( ; 0 < size1; size1 = in.arrayNext()) {
        for ( ; size1 != 0; size1--) {
          java.lang.CharSequence e1 = (ga1 != null ? ga1.peek() : null);
          e1 = in.readString(e1 instanceof Utf8 ? (Utf8)e1 : null);
          a1.add(e1);
        }
      }

      this.freePreviewAvailable = in.readBoolean();

      this.lifeCycleStatus = com.emi.events.bookPublished.BookLifeCycleStatus.values()[in.readEnum()];

      if (in.readIndex() != 1) {
        in.readNull();
        this.visibilityStatus = null;
      } else {
        this.visibilityStatus = com.emi.events.bookPublished.BookVisibilityStatus.values()[in.readEnum()];
      }

      this.publishedAt = in.readLong();

    } else {
      for (int i = 0; i < 10; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.bookId = in.readString(this.bookId instanceof Utf8 ? (Utf8)this.bookId : null);
          break;

        case 1:
          this.title = in.readString(this.title instanceof Utf8 ? (Utf8)this.title : null);
          break;

        case 2:
          this.description = in.readString(this.description instanceof Utf8 ? (Utf8)this.description : null);
          break;

        case 3:
          this.price = in.readDouble();
          break;

        case 4:
          long size0 = in.readArrayStart();
          java.util.List<java.lang.CharSequence> a0 = this.authorNames;
          if (a0 == null) {
            a0 = new SpecificData.Array<java.lang.CharSequence>((int)size0, SCHEMA$.getField("authorNames").schema());
            this.authorNames = a0;
          } else a0.clear();
          SpecificData.Array<java.lang.CharSequence> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.CharSequence>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              java.lang.CharSequence e0 = (ga0 != null ? ga0.peek() : null);
              e0 = in.readString(e0 instanceof Utf8 ? (Utf8)e0 : null);
              a0.add(e0);
            }
          }
          break;

        case 5:
          long size1 = in.readArrayStart();
          java.util.List<java.lang.CharSequence> a1 = this.genres;
          if (a1 == null) {
            a1 = new SpecificData.Array<java.lang.CharSequence>((int)size1, SCHEMA$.getField("genres").schema());
            this.genres = a1;
          } else a1.clear();
          SpecificData.Array<java.lang.CharSequence> ga1 = (a1 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.CharSequence>)a1 : null);
          for ( ; 0 < size1; size1 = in.arrayNext()) {
            for ( ; size1 != 0; size1--) {
              java.lang.CharSequence e1 = (ga1 != null ? ga1.peek() : null);
              e1 = in.readString(e1 instanceof Utf8 ? (Utf8)e1 : null);
              a1.add(e1);
            }
          }
          break;

        case 6:
          this.freePreviewAvailable = in.readBoolean();
          break;

        case 7:
          this.lifeCycleStatus = com.emi.events.bookPublished.BookLifeCycleStatus.values()[in.readEnum()];
          break;

        case 8:
          if (in.readIndex() != 1) {
            in.readNull();
            this.visibilityStatus = null;
          } else {
            this.visibilityStatus = com.emi.events.bookPublished.BookVisibilityStatus.values()[in.readEnum()];
          }
          break;

        case 9:
          this.publishedAt = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










