version: "3.8"

services:
    api-gateway:
        build:
            context: ../..
            dockerfile: Api-gateway/Dockerfile
        container_name: api-gateway
        restart: on-failure
        environment:
            SPRING_APPLICATION_NAME: api-gateway
            SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/Library-realm/protocol/openid-connect/certs
        ports:
            - "8089:8080"
        networks:
            - Library-net

networks:
  Library-net:
    external: true