version: "3.8"

services:
    catalog-service:
        build:
            context: ../..
            dockerfile: Catalog-Service/Dockerfile
        container_name: catalog-service
        restart: on-failure
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/catalogservice_db
            SPRING_DATASOURCE_USERNAME: postgres
            SPRING_DATASOURCE_PASSWORD: postgres
            SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/Library-realm/protocol/openid-connect/certs
        ports:
            - "8082:8080"
        networks:
            - Library-net

networks:
  Library-net:
    external: true
    name: Library-net