package com.emi.payment_service.ResponseDto;

import java.math.BigDecimal;

import com.emi.payment_service.enums.GatewayPaymentStatus;

import io.swagger.v3.oas.annotations.media.Schema;




@Schema(description = "Response returned after processing a payment through the gateway")
public record GatewayResponse(

        @Schema(
            description = "Unique transaction identifier generated by the payment gateway",
            example = "txn_9f8a7b6c5d"
        )
        String transactionId,

        @Schema(
            description = "Current status of the payment transaction",
            example = "SUCCESS"
        )
        GatewayPaymentStatus status,

        @Schema(
            description = "Final transaction amount processed",
            example = "499.99"
        )
        BigDecimal amount

) {}