spring.application.name=api-gateway
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/Library-realm
#Swagger -
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.urls[0].name=Authoring-Service
springdoc.swagger-ui.urls[0].url=/aggregate/authoring-service/api-docs
springdoc.swagger-ui.urls[1].name=Catalog-Service
springdoc.swagger-ui.urls[1].url=/aggregate/catalog-service/api-docs
springdoc.swagger-ui.urls[2].name=User-Service
springdoc.swagger-ui.urls[2].url=/aggregate/user-service/api-docs
springdoc.swagger-ui.urls[3].name=Author-Service
springdoc.swagger-ui.urls[3].url=/aggregate/author-service/api-docs
springdoc.swagger-ui.urls[4].name=Order-Service
springdoc.swagger-ui.urls[4].url=/aggregate/order-service/api-docs
springdoc.swagger-ui.urls[5].name=Payment-Service
springdoc.swagger-ui.urls[5].url=/aggregate/payment-service/api-docs
springdoc.swagger-ui.urls[6].name=Search-Service
springdoc.swagger-ui.urls[6].url=/aggregate/search-service/api-docs



